### ISSUE TITLE
Add service configuration loading and mapping

### ISSUE THREAD

**Issue by floriansattler** [commercetools/commercetools-paypal-plus-integration#3]
The config will be smth like this:

**YAML example**
```yml
tenants=bulls,pegasus
tenant.bulls:
  ctp.client:
    projectKey: blah-blah-bulls
    clientId: blah-blah-bulls
    clientSecret: blah-blah-bulls
  paypalPlus.client:
    id: blah-blah-bulls
    secret: blah-blah-bulls
    mode: sandbox/live

tenant.pegasus:
  ctp.client:
    projectKey: blah-blah-pegasus
    clientId: blah-blah-pegasus
    clientSecret: blah-blah-pegasus
  paypalPlus.client:
    id: blah-blah-pegasus
    secret: blah-blah-pegasus
    mode: sandbox/live
```

Environment variables example:
```bash
TENANTS=bulls,pegasus
TENANT_bulls_CTP_CLIENT_PROJECTKEY=blah-blah-bulls
TENANT_bulls_CTP_CLIENT_CLIENTID=blah-blah-bulls
TENANT_bulls_CTP_CLIENT_CLIENTSECRET=blah-blah-bulls
TENANT_bulls_PAYPALPLUS_CLIENT_ID=blah-blah-bulls
TENANT_bulls_PAYPALPLUS_CLIENT_SECRET=blah-blah-bulls
TENANT_bulls_PAYPALPLUS_CLIENT_MODE=sandbox/live
TENANT_pegasus_CTP_CLIENT_PROJECTKEY=blah-blah-pegasus
TENANT_pegasus_CTP_CLIENT_CLIENTID=blah-blah-pegasus
TENANT_pegasus_CTP_CLIENT_CLIENTSECRET=blah-blah-pegasus
TENANT_pegasus_PAYPALPLUS_CLIENT_ID=blah-blah-pegasus
TENANT_pegasus_PAYPALPLUS_CLIENT_SECRET=blah-blah-pegasus
TENANT_pegasus_PAYPALPLUS_CLIENT_MODE=sandbox/live

```
